[package]
name = "ALC"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ALC"
path = "src/main.rs"

[dependencies]
artificial-core = { path = "../artificial-core" }
artificial-vm = { path = "../artificial-vm" }
